using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Text;
using sacco.Lib;



namespace sacco_test
{
    [TestClass]
    public class AccountData_test
    {
        [TestMethod]
        public void TestAccountData()
        {
            StdCoin coin;
            String s;

            AccountData acData = new AccountData(accountNumber: "MyAccountNumber", 
                                sequence: "MyAccountSequence", 
                                coins: new List<StdCoin> { new StdCoin(denom: "uDenom1", amount: "uAmount1"), new StdCoin(denom: "uDenom2", amount: "uAmount2") });
            // Verify the contents
            Assert.AreEqual(acData.accountNumber, "MyAccountNumber");
            Assert.AreEqual(acData.sequence, "MyAccountSequence");
            coin = acData.coins.Find(c => c.denom == "uDenom1");
            Assert.AreEqual(coin.amount, "uAmount1");
            coin = acData.coins.Find(c => c.denom == "uDenom2");
            Assert.AreEqual(coin.amount, "uAmount2");
            // Check the method
            s = acData.ToString();
            // Copying here the string generated by Dart
            // Assert.AreEqual(s, "number: MyAccountNumber, sequence: MyAccountSequence, coins: [Instance of 'StdCoin', Instance of 'StdCoin']");
            // *** The string generated in the Dart environment is different fro the one in C# - Is this a problem?
            Assert.AreEqual(s, "number: MyAccountNumber, sequence: MyAccountSequence, coins: System.Collections.Generic.List`1[sacco.Lib.StdCoin]");
        }
    }
}
