using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Text;
using Newtonsoft.Json;
using sacco.Lib;

namespace sacco_test
{
    [TestClass]
    public class AccountDataRetriever_test
    {
        [TestMethod]
        public void TestAccountDataParsing()
        {
            StdCoin coin;
            String s;
            

            // Create the account
            AccountData acData = new AccountData(accountNumber: "MyAccountNumber",
                                sequence: "MyAccountSequence",
                                coins: new List<StdCoin> { new StdCoin(denom: "uDenom1", amount: "uAmount1"), new StdCoin(denom: "uDenom2", amount: "uAmount2") });
            // Create the fake Server Answer (hope this is right!!)
            Dictionary<String, Object> fakeResult = new Dictionary<String, Object> { { "type", "cosmos-sdk/Account" }, { "value", acData.toJson() } };
            Dictionary<String, Object> fakeAnswer = new Dictionary<String, Object> { { "Height", "0" }, { "result", fakeResult } } ;
            // json encode it in a test string
            String testResponse = JsonConvert.SerializeObject(fakeAnswer);

            // Test the method
            AccountData acParsed = AccountDataRetrieval.parseServerReturnedAccount(testResponse);

            // Verify the contents
            Assert.AreEqual(acParsed.accountNumber, "MyAccountNumber");
            Assert.AreEqual(acParsed.sequence, "MyAccountSequence");
            coin = acParsed.coins.Find(c => c.denom == "uDenom1");
            Assert.AreEqual(coin.amount, "uAmount1");
            coin = acParsed.coins.Find(c => c.denom == "uDenom2");
            Assert.AreEqual(coin.amount, "uAmount2");
            // Check the method
            s = acParsed.ToString();
            // Copying here the string generated by Dart
            // Assert.AreEqual(s, "number: MyAccountNumber, sequence: MyAccountSequence, coins: [Instance of 'StdCoin', Instance of 'StdCoin']");
            // *** The string generated in the Dart environment is different fro the one in C# - Is this a problem?
            Assert.AreEqual(s, "number: MyAccountNumber, sequence: MyAccountSequence, coins: System.Collections.Generic.List`1[sacco.Lib.StdCoin]");
        }
    }
}
